# Generated by Django 3.2.6 on 2022-05-26 10:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20220526_0334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_detail',
            new_name='Profile',
        ),
    ]
