# Generated by Django 3.2.6 on 2022-05-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_user_detail_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exp_added',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateTime_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='exp',
            field=models.IntegerField(blank=True, choices=[(10, 'Easy'), (20, 'Average'), (50, 'Complex'), (100, 'BOSS')], default=10, null=True),
        ),
    ]
