# Generated by Django 3.2.6 on 2022-06-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_level_profile_exp_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='exp_sum',
            new_name='level',
        ),
    ]
