# Generated by Django 3.2.6 on 2022-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_exp_sum_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
